/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUITest;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.table.DefaultTableModel;

import funcionalities.Form;
import objects.User;

/**
 *
 * @author Ricardo
 */
public class ProblemProcess3 extends javax.swing.JPanel {

	private ProblemProcess4 problemPanel;
	private Form form;
	private int variableCounter = 0;
	private DefaultTableModel variableTableModel = new DefaultTableModel();
	private String name;
	private String description;
	private User userLoggedIn;

	/**
	 * Creates new form ProblemProcess3
	 */
	public ProblemProcess3(Form form,String name, String description, User userLoggedIn) {
		this.name= name;
		this.description = description;
		this.userLoggedIn = userLoggedIn;
		this.form = form;
		initComponents();
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		nameLabel = new javax.swing.JLabel();
		quantityLabel = new javax.swing.JLabel();
		nameTextField = new javax.swing.JTextField();
		quantityTextField = new javax.swing.JTextField();
		typeLabel = new javax.swing.JLabel();
		minValueLabel = new javax.swing.JLabel();
		minValueTextField = new javax.swing.JTextField();
		maxValueLabel = new javax.swing.JLabel();
		maxValueTextField = new javax.swing.JTextField();
		variablesScrollPane = new javax.swing.JScrollPane();
		variableTable = new javax.swing.JTable();
		generateButton = new javax.swing.JButton();
		removeButton = new javax.swing.JButton();
		titleLabel = new javax.swing.JLabel();
		nextButton = new javax.swing.JButton();
		typeComboBox = new javax.swing.JComboBox<>();

		setBackground(new java.awt.Color(255, 255, 255));

		nameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		nameLabel.setText("Name");

		quantityLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		quantityLabel.setText("Quantity");

		nameTextField.setForeground(new java.awt.Color(153, 153, 153));
		//nameTextField.setText("e.g. rule ");
		nameTextField.setToolTipText("");
		nameTextField.setMargin(new java.awt.Insets(2, 15, 2, 2));
		nameTextField.setName(""); // NOI18N

		quantityTextField.setForeground(new java.awt.Color(153, 153, 153));
		//quantityTextField.setText("e.g. 20");
		quantityTextField.setToolTipText("");
		quantityTextField.setMargin(new java.awt.Insets(2, 15, 2, 2));

		typeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		typeLabel.setText("Type");

		minValueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		minValueLabel.setText("Mininum Value");

		minValueTextField.setForeground(new java.awt.Color(153, 153, 153));
		//minValueTextField.setText("e.g. 1");
		minValueTextField.setToolTipText("");
		minValueTextField.setMargin(new java.awt.Insets(2, 15, 2, 2));

		maxValueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		maxValueLabel.setText("Maximum Value");

		maxValueTextField.setForeground(new java.awt.Color(153, 153, 153));
		//maxValueTextField.setText("e.g. 10");
		maxValueTextField.setToolTipText("");
		maxValueTextField.setMargin(new java.awt.Insets(2, 15, 2, 2));
		maxValueTextField.setName(""); // NOI18N

		variableTableModel.addColumn("Name");
		variableTableModel.addColumn("Type");
		variableTableModel.addColumn("Min Value");
		variableTableModel.addColumn("Max Value");
		variableTable.setModel(variableTableModel);
		variablesScrollPane.setViewportView(variableTable);

		generateButton.setText("Generate");

		removeButton.setText("Remove");

		titleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLabel.setText("Create variables");

		nextButton.setIcon(new javax.swing.ImageIcon("img\\arrowRight.png")); // NOI18N
		nextButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		nextButton.setFocusable(false);

		typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "integer", "double", "binary" }));

		nextButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				nextPanel();				
			}
		});
		
		generateButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				createVariables();
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addGap(22, 22, 22)
														.addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup()
														.addGap(43, 43, 43)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																.addComponent(minValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(31, 31, 31)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																.addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
																.addComponent(minValueTextField)
																.addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
														.addGap(26, 26, 26)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addGroup(layout.createSequentialGroup()
																		.addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(maxValueLabel)
																		.addGap(18, 18, 18)
																		.addComponent(maxValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addGap(0, 40, Short.MAX_VALUE)))
						.addContainerGap())
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(235, 235, 235))
				.addGroup(layout.createSequentialGroup()
						.addGap(23, 23, 23)
						.addComponent(variablesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(37, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(20, 20, 20)
						.addComponent(titleLabel)
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(minValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(minValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(maxValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(maxValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(13, 13, 13)
						.addComponent(variablesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(generateButton)
								.addComponent(removeButton))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(13, Short.MAX_VALUE))
				);
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Method to remove the current panel and add the next one
	 */
	
	private void nextPanel() {
		problemPanel = new ProblemProcess4(form, name, description, variableTableModel,userLoggedIn);
		form.create(problemPanel);
	}
	
	/**
	 * Method to create variables based on quantity selected
	 */
	
    private void createVariables() {
    	int variableQuantityInteger = Integer.parseInt(quantityTextField.getText());
    	for(int i = 0; i <  variableQuantityInteger ; i++) {
    		variableCounter++;
    		variableTableModel.addRow(new Object[]{nameTextField.getText()+" "+variableCounter,typeComboBox.getSelectedItem(),minValueTextField.getText(),maxValueTextField.getText()});	   		
    	} 	
    }


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton generateButton;
	private javax.swing.JLabel maxValueLabel;
	private javax.swing.JTextField maxValueTextField;
	private javax.swing.JLabel minValueLabel;
	private javax.swing.JTextField minValueTextField;
	private javax.swing.JLabel nameLabel;
	private javax.swing.JTextField nameTextField;
	private javax.swing.JButton nextButton;
	private javax.swing.JLabel quantityLabel;
	private javax.swing.JTextField quantityTextField;
	private javax.swing.JButton removeButton;
	private javax.swing.JLabel titleLabel;
	private javax.swing.JComboBox<String> typeComboBox;
	private javax.swing.JLabel typeLabel;
	private javax.swing.JTable variableTable;
	private javax.swing.JScrollPane variablesScrollPane;
	// End of variables declaration//GEN-END:variables
}
