/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUITest;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicBorders.RadioButtonBorder;
import javax.swing.table.DefaultTableModel;

import files.XMLOperations;
import funcionalities.Form;
import objects.User;

/**
 *
 * @author Ricardo
 */
public class ProblemProcess4 extends javax.swing.JPanel {

	private WelcomePage welcomePage;
	private XMLOperations xml = new XMLOperations();
	private Form form;
	private String name;
	private String description;
	private DefaultTableModel variableList;
	private User userLoggedIn;
	private ButtonGroup radioButtonGroup = new ButtonGroup();
		
    /**
     * Creates new form ProblemProcess4
     */
    public ProblemProcess4(Form form, String name, String description, DefaultTableModel variableList,User userLoggedIn) {
    	this.form = form;
    	this.name=name;
    	this.description=description;
    	this.variableList=variableList;
    	this.userLoggedIn = userLoggedIn;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        invalidValueLabel = new javax.swing.JLabel();
        firstInvalidValueTextField = new javax.swing.JTextField();
        timeComboBox = new javax.swing.JComboBox<>();
        secondInvalidValueTextField = new javax.swing.JTextField();
        intervalRButton = new javax.swing.JRadioButton();
        singleRButton = new javax.swing.JRadioButton();
        toLabel = new javax.swing.JLabel();
        finishButton = new javax.swing.JButton();
        waitTimeTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Choose the restrictions");

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timeLabel.setText("Wait Time");

        invalidValueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        invalidValueLabel.setText("Invalid Values");

        firstInvalidValueTextField.setForeground(new java.awt.Color(153, 153, 153));
        //firstInvalidValueTextField.setText("e.g. 2");
        firstInvalidValueTextField.setToolTipText("");
        firstInvalidValueTextField.setMargin(new java.awt.Insets(2, 15, 2, 2));

        timeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seconds", "minutes", "hours", "days" }));

        secondInvalidValueTextField.setForeground(new java.awt.Color(153, 153, 153));
        secondInvalidValueTextField.setMargin(new java.awt.Insets(2, 15, 2, 2));
        //secondInvalidValueTextField.setText("e.g. 4");

        intervalRButton.setText("Interval");

        singleRButton.setText("Single Value");

        toLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        toLabel.setText("to");

        finishButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        finishButton.setText("Finish");
        finishButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        finishButton.setFocusable(false);

        waitTimeTextField.setForeground(new java.awt.Color(153, 153, 153));
        //waitTimeTextField.setText("e.g. 10");
        waitTimeTextField.setToolTipText("");
        waitTimeTextField.setMargin(new java.awt.Insets(2, 15, 2, 2));
        
        radioButtonGroup.add(intervalRButton);
        radioButtonGroup.add(singleRButton);
        firstInvalidValueTextField.setEnabled(false);
        secondInvalidValueTextField.setEnabled(false);
        
        intervalRButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				firstInvalidValueTextField.setEnabled(true);
				secondInvalidValueTextField.setEnabled(true);
			}
		});
        
        singleRButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				secondInvalidValueTextField.setEnabled(false);
			}
		});
        
        
        finishButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				createXML();				
			}
		});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(invalidValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(intervalRButton)
                                .addGap(54, 54, 54)
                                .addComponent(singleRButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstInvalidValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(toLabel)
                                .addGap(27, 27, 27)
                                .addComponent(secondInvalidValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(waitTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waitTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invalidValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intervalRButton)
                    .addComponent(singleRButton))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstInvalidValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toLabel)
                    .addComponent(secondInvalidValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextPanel() {
    	 welcomePage = new WelcomePage(userLoggedIn);
    	form.create(welcomePage);
    }
    
    private void createXML() {
    	if(singleRButton.isSelected()) {
    		xml.writeXML(name, variableList ,description, waitTimeTextField.getText() + " " + timeComboBox.getSelectedItem() , firstInvalidValueTextField.getText());
    	} else {
    		System.out.println("interval");
    		xml.writeXML(name, variableList ,description, waitTimeTextField.getText() + " " + timeComboBox.getSelectedItem() , firstInvalidValueTextField.getText(),secondInvalidValueTextField.getText());
    	}
    	
		
		JOptionPane.showMessageDialog(null, "XML Created");
    }
	

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finishButton;
    private javax.swing.JTextField firstInvalidValueTextField;
    private javax.swing.JRadioButton intervalRButton;
    private javax.swing.JLabel invalidValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField secondInvalidValueTextField;
    private javax.swing.JRadioButton singleRButton;
    private javax.swing.JComboBox<String> timeComboBox;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField waitTimeTextField;
    // End of variables declaration//GEN-END:variables
}
