/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import funcionalities.Email;
import objects.User;

/**
 *
 * @author Ricardo
 */
public class EmailPanel extends javax.swing.JPanel {

	private User userLoggedIn;
	/**
	 * Creates new form EmailPanel
	 */
	public EmailPanel(User userLoggedIn) {
		this.userLoggedIn = userLoggedIn;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	public void initComponents() {

		emailLabel = new javax.swing.JLabel();
		sendEmailButton = new javax.swing.JButton();
		subjectTF = new javax.swing.JTextField();
		subjectLabel = new javax.swing.JLabel();
		messageLabel = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		messageTF = new javax.swing.JTextArea();

		setBackground(new java.awt.Color(255, 255, 255));
		setPreferredSize(new java.awt.Dimension(780, 420));

		emailLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		emailLabel.setText("Email ");

		sendEmailButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		sendEmailButton.setText("Send Email");

		sendEmailButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				email.sendEmail(userLoggedIn.getEmail(), userLoggedIn.getPassword(), subjectTF.getText(),messageTF.getText());
				subjectTF.setText("");
				messageTF.setText("");

			}
		});

		subjectTF.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				subjectTFActionPerformed(evt);
			}
		});


		subjectTF.setMargin(new java.awt.Insets(2, 15, 2, 2));
		subjectTF.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				subjectTFActionPerformed(evt);
			}
		});

		subjectLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		subjectLabel.setText("Subject");

		messageLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		messageLabel.setText("Message");

		messageTF.setColumns(20);
		messageTF.setRows(5);
		messageTF.setMargin(new java.awt.Insets(2, 15, 2, 2));
		jScrollPane1.setViewportView(messageTF);



		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGap(0, 138, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(subjectTF)
								.addComponent(subjectLabel, javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(messageLabel, javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(85, 85, 85))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addComponent(sendEmailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap())
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(285, 285, 285))))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(21, 21, 21)
						.addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(31, 31, 31)
						.addComponent(subjectLabel)
						.addGap(18, 18, 18)
						.addComponent(subjectTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(messageLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
						.addComponent(sendEmailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				);
	}// </editor-fold>//GEN-END:initComponents

	private void subjectTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTFActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_subjectTFActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel emailLabel;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel messageLabel;
	private javax.swing.JTextArea messageTF;
	private javax.swing.JButton sendEmailButton;
	private javax.swing.JLabel subjectLabel;
	private javax.swing.JTextField subjectTF;
	// End of variables declaration//GEN-END:variables
	private Email email = new Email();
}
