/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.nio.file.FileSystemLoopException;
import java.util.ArrayList;

import org.w3c.dom.Node;

import files.XMLOperations;
import funcionalities.Optimization;
import jMetal.AntiSpamFilterAutomaticConfiguration;
import objects.Problem;

/**
 *
 * @author Ricardo
 */
public class OptimizationPanel extends javax.swing.JPanel {

	/**
	 * Creates new form OptimizePanel
	 */
	public OptimizationPanel() {
		initComponents();
	}



	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		optimizationTitleLabel = new javax.swing.JLabel();
		problemLabel = new javax.swing.JLabel();
		problemCB = new javax.swing.JComboBox<>();
		algorithmLabel = new javax.swing.JLabel();
		algorithmCB = new javax.swing.JComboBox<>();
		jScrollPane1 = new javax.swing.JScrollPane();
		variablesTable = new javax.swing.JTable();
		variaveisTitleLabel = new javax.swing.JLabel();
		varNameTF = new javax.swing.JTextField();
		varNameLabel = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jarFileTF = new javax.swing.JTextField();
		addButton = new javax.swing.JButton();
		optimizeButton = new javax.swing.JButton();
		manualConfigRB = new javax.swing.JRadioButton();
		automaticConfigRB = new javax.swing.JRadioButton();

		setPreferredSize(new java.awt.Dimension(660, 628));

		optimizationTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		optimizationTitleLabel.setText("Optimization Panel");

		problemLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		problemLabel.setText("Problem");

		//problemCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		algorithmLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		algorithmLabel.setText("Algorithm");

		algorithmCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		variablesTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object [][] {
					{null, null},
					{null, null},
					{null, null},
					{null, null}
				},
				new String [] {
						"Name", "JAR File"
				}
				) {
			Class[] types = new Class [] {
					java.lang.String.class, java.lang.Object.class
			};

			public Class getColumnClass(int columnIndex) {
				return types [columnIndex];
			}
		});
		jScrollPane1.setViewportView(variablesTable);

		variaveisTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		variaveisTitleLabel.setText("Variables");

		varNameLabel.setText("Name");

		jLabel3.setText("JAR");

		addButton.setText("Add");

		optimizeButton.setText("Done");

		manualConfigRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		manualConfigRB.setText("Manual Configuration");

		automaticConfigRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		automaticConfigRB.setText("Automatic Configuration");

		/*  **************************** METODOS CRIADOS **************************** */

		File[] fileList = optimization.searchFiles();

		for (File f: fileList) {
			problemCB.addItem(f.getName());
		}

		optimizeButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				System.out.println(problemCB.getSelectedItem());			
				//ALTERAR ISTO PARA UM METODO MUITO CODIGO
				// isto recebe o ficheiro selecionado e guarda os valores nas variaveis
				//
				//
		    //  \/

				try {
					ArrayList variableArray = new ArrayList();
					
					//model.setRowCount(0);
					File file = (File) problemCB.getSelectedItem();
					Node[] xmlFile = xmlOperations.readXML(file);
					String name = xmlFile[0].getTextContent().toString();
					String description = xmlFile[1].getTextContent().toString();
					String waitTime = xmlFile[2].getTextContent().toString();
					
			

					String variableName = "";
					String variableType = "";
					String variableMinimumValue = "";
					String variableMaximumValue = "";
					String invalidValue = "";
					int variableCounter = 0;

					for(Node n : xmlFile) {

						if(n.getNodeName().equals("variable") )	{
							variableCounter++;
							for(int i=0; i < n.getChildNodes().getLength(); i++) {
								System.out.println(n.getChildNodes().item(i).getTextContent());
								// model.addElement(n.getChildNodes().item(i).getTextContent());
								if(n.getChildNodes().item(i).getNodeName().equals("name"))
									variableName = n.getChildNodes().item(i).getTextContent();
								if(n.getChildNodes().item(i).getNodeName().equals("type"))
									variableType = n.getChildNodes().item(i).getTextContent();
								if(n.getChildNodes().item(i).getNodeName().equals("minimumValue"))
									variableMinimumValue = n.getChildNodes().item(i).getTextContent();
								if(n.getChildNodes().item(i).getNodeName().equals("maximumValue"))
									variableMaximumValue = n.getChildNodes().item(i).getTextContent();
							}
						}

						if(n.getNodeName().equals("invalidValues"))
							invalidValue = n.getTextContent();

					}
					
					problem = new Problem(name, description, Integer.parseInt(waitTime), Integer.parseInt(invalidValue), variableCounter);
					antiSpamFilter.init(problem);
					
				} catch (Exception e1) {
					// TODO: handle exception
				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(236, 236, 236)
						.addComponent(optimizationTitleLabel)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(manualConfigRB)
						.addGap(90, 90, 90)
						.addComponent(automaticConfigRB)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(36, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(problemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(algorithmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(variaveisTitleLabel))
										.addGap(30, 30, 30)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(problemCB, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(algorithmCB, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(layout.createSequentialGroup()
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(varNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(18, 18, 18)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jarFileTF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(varNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(layout.createSequentialGroup()
														.addGap(153, 153, 153)
														.addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addGap(26, 26, 26))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(optimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(209, 209, 209))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(36, 36, 36)
						.addComponent(optimizationTitleLabel)
						.addGap(37, 37, 37)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(automaticConfigRB)
								.addComponent(manualConfigRB))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(problemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(problemCB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(34, 34, 34)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(algorithmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(algorithmCB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(46, 46, 46)
						.addComponent(variaveisTitleLabel)
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(varNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(varNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jarFileTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addComponent(addButton)
										.addGap(12, 12, 12))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(45, 45, 45)
						.addComponent(optimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(23, 23, 23))
				);
	}// </editor-fold>//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addButton;
	private javax.swing.JComboBox<String> algorithmCB;
	private javax.swing.JLabel algorithmLabel;
	private javax.swing.JRadioButton automaticConfigRB;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jarFileTF;
	private javax.swing.JRadioButton manualConfigRB;
	private javax.swing.JLabel optimizationTitleLabel;
	private javax.swing.JButton optimizeButton;
	private javax.swing.JComboBox<String> problemCB;
	private javax.swing.JLabel problemLabel;
	private javax.swing.JLabel varNameLabel;
	private javax.swing.JTextField varNameTF;
	private javax.swing.JTable variablesTable;
	private javax.swing.JLabel variaveisTitleLabel;
	// End of variables declaration//GEN-END:variables
	private Optimization optimization = new Optimization();
	private XMLOperations xmlOperations = new XMLOperations();
	private AntiSpamFilterAutomaticConfiguration antiSpamFilter = new AntiSpamFilterAutomaticConfiguration();
	private Problem problem;

}
