/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import files.XMLOperations;

/**
 *
 * @author Ricardo
 */
public class ProblemPanel extends javax.swing.JPanel {

	/**
	 * Creates new form ProblemPanelnew
	 */
	public ProblemPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		nameLabel = new javax.swing.JLabel();
		waitTimeLabel = new javax.swing.JLabel();
		waitTimeTF = new javax.swing.JTextField();
		timeComboBox = new javax.swing.JComboBox<>();
		invalidValueLabel = new javax.swing.JLabel();
		nameTF = new javax.swing.JTextField();
		invalidValueTF = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		variablesTable = new javax.swing.JTable();
		variableNameLabel = new javax.swing.JLabel();
		variableNameTF = new javax.swing.JTextField();
		variableMinLabel = new javax.swing.JLabel();
		variableMinValueTF = new javax.swing.JTextField();
		variableMaxLabel = new javax.swing.JLabel();
		variableMaxValueTF = new javax.swing.JTextField();
		variableTypeTF = new javax.swing.JTextField();
		variableTyleLabel = new javax.swing.JLabel();
		addVariableButton = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		descriptionTA = new javax.swing.JTextArea();
		jLabel8 = new javax.swing.JLabel();
		sendButton = new javax.swing.JButton();
		model = new javax.swing.table.DefaultTableModel();

		addVariableButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {

				model.addRow(new Object[]{variableNameTF.getText(),variableTypeTF.getText(),variableMinValueTF.getText(),variableMaxValueTF.getText()});
				variableNameTF.setText("");
				variableTypeTF.setText("");
				variableMinValueTF.setText("");
				variableMaxValueTF.setText("");
			}
		});


		sendButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				xml.writeXML(nameTF.getText(), model ,descriptionTA.getText(), waitTimeTF.getText() + " " + timeComboBox.getSelectedItem() , invalidValueTF.getText());

				JOptionPane.showMessageDialog(sendButton, "XML Created");

			}
		});

		nameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		nameLabel.setText("Name");

		waitTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		waitTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		waitTimeLabel.setText("Wait Time");

		waitTimeTF.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				waitTimeTFActionPerformed(evt);
			}
		});

		timeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "minutes", "hours", "days" }));
		timeComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				timeComboBoxActionPerformed(evt);
			}
		});

		invalidValueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		invalidValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		invalidValueLabel.setText("Invalid Value");

		//Nome das colunas da jtable
		model.addColumn("Name");
		model.addColumn("Type");
		model.addColumn("Min Value");
		model.addColumn("Max Value");

		variablesTable.setModel(model);
		jScrollPane1.setViewportView(variablesTable);

		variableNameLabel.setText("Name");
		variableMinLabel.setText("Min Value");
		variableMinValueTF.setName(""); // NOI18N
		variableMaxLabel.setText("Max Value");
		variableTyleLabel.setText("Type");

		addVariableButton.setText("Add");

		descriptionTA.setColumns(20);
		descriptionTA.setRows(5);
		jScrollPane2.setViewportView(descriptionTA);

		jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel8.setText("Description");

		sendButton.setText("Send");
		sendButton.setToolTipText("");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(28, 28, 28)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(waitTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(invalidValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(invalidValueTF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(layout.createSequentialGroup()
														.addComponent(waitTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																		.addComponent(variableMaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(variableMinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(variableMinValueTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(variableMaxValueTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																		.addComponent(variableNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(variableTyleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(variableTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(variableNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addComponent(addVariableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
										.addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jScrollPane2))
						.addContainerGap(40, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(52, 52, 52)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(8, 8, 8)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(waitTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(waitTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGap(9, 9, 9)
										.addComponent(invalidValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(invalidValueTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(28, 28, 28)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(variableNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(variableNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(variableTyleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(variableTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(variableMinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(variableMinValueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(variableMaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(variableMaxValueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(addVariableButton))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
						.addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				);
	}// </editor-fold>//GEN-END:initComponents

	private void timeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeComboBoxActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_timeComboBoxActionPerformed

	private void waitTimeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitTimeTFActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_waitTimeTFActionPerformed

	private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_nameTFActionPerformed

	private void invalidValueTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invalidValueTFActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_invalidValueTFActionPerformed

	private void variableNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variableNameTFActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_variableNameTFActionPerformed

	private void variableMinValueTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variableMinValueTFActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_variableMinValueTFActionPerformed

	private void variableMaxValueTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variableMaxValueTFActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_variableMaxValueTFActionPerformed

	private void variableTypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variableTypeTFActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_variableTypeTFActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addVariableButton;
	private javax.swing.JTextArea descriptionTA;
	private javax.swing.JLabel invalidValueLabel;
	private javax.swing.JTextField invalidValueTF;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel nameLabel;
	private javax.swing.JTextField nameTF;
	private javax.swing.JButton sendButton;
	private javax.swing.JComboBox<String> timeComboBox;
	private javax.swing.JLabel variableMaxLabel;
	private javax.swing.JTextField variableMaxValueTF;
	private javax.swing.JLabel variableMinLabel;
	private javax.swing.JTextField variableMinValueTF;
	private javax.swing.JLabel variableNameLabel;
	private javax.swing.JTextField variableNameTF;
	private javax.swing.JLabel variableTyleLabel;
	private javax.swing.JTextField variableTypeTF;
	private javax.swing.JTable variablesTable;
	private javax.swing.JLabel waitTimeLabel;
	private javax.swing.JTextField waitTimeTF;
	// End of variables declaration//GEN-END:variables
	private javax.swing.table.DefaultTableModel model;
	private XMLOperations xml = new XMLOperations();
}
