/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import funcionalities.Register;

/**
 *
 * @author Ricardo
 */
public class RegisterPanel extends javax.swing.JPanel {

	/**
	 * Creates new form RegistarPanelnew
	 */
	public RegisterPanel(JFrame frame, JPanel loginPanel) {
		this.frame = frame;
		this.loginPanel = loginPanel;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		
		frame.add(this);

		usernameLabel = new javax.swing.JLabel();
		userNameTF = new javax.swing.JTextField();
		passwordLabel = new javax.swing.JLabel();
		emailTF = new javax.swing.JTextField();
		emailLabel = new javax.swing.JLabel();
		confirmPasswordLabel = new javax.swing.JLabel();
		registerButton = new javax.swing.JButton();
		passwordTF = new javax.swing.JPasswordField();
		confirmPasswordTF = new javax.swing.JPasswordField();
		aceptTermsCheckBox = new javax.swing.JCheckBox();
		showTermsButton = new javax.swing.JButton();

		usernameLabel.setText("Username");

		passwordLabel.setText("Password");

		emailLabel.setText("Email");

		confirmPasswordLabel.setText("Confirm Password");

		registerButton.setText("Register");

		aceptTermsCheckBox.setText("I accept the terms of use");

		showTermsButton.setForeground(new java.awt.Color(51, 102, 255));
		showTermsButton.setText("Terms of use");
		showTermsButton.setBorder(null);
		showTermsButton.setContentAreaFilled(false);
		
		showTermsButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				Agreement agreementFrame = new Agreement();
				agreementFrame.init();
				
			}
		});

		registerButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {

				if(passwordTF.getText().equals(confirmPasswordTF.getText()) && !userNameTF.getText().equals("") && !emailTF.getText().equals("") && !passwordTF.getText().equals("") && !confirmPasswordTF.getText().equals("") && aceptTermsCheckBox.isSelected()){

					register = new Register(userNameTF.getText(), emailTF.getText(), passwordTF.getText());
					register.newRegister();

					JOptionPane.showMessageDialog(null, "Register sucessfully!");

					RegisterPanel.this.setVisible(false);
					loginPanel.setVisible(true);
				}

				else{
					if(!aceptTermsCheckBox.isSelected()) {
						JOptionPane.showMessageDialog(null, "You didn´t accept the terms of use!");
					}else {

						if(userNameTF.getText().equals(""))
							JOptionPane.showMessageDialog(null, "You didn´t enter the username!");
						else{

							if(emailTF.getText().equals(""))
								JOptionPane.showMessageDialog(null, "You didn´t enter the email!");
							else{
								if(passwordTF.getText().equals("") || confirmPasswordTF.getText().equals(""))
									JOptionPane.showMessageDialog(null, "You didn´t enter or confirm  the password!");
								else{
									if(!(passwordTF.getText().equals(confirmPasswordTF.getText())))
										JOptionPane.showMessageDialog(null, "Passwords aren´t equals!");
								}
							}
						}
					}
				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGap(21, 21, 21)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(confirmPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(aceptTermsCheckBox)))
								.addGroup(layout.createSequentialGroup()
										.addGap(59, 59, 59)
										.addComponent(showTermsButton)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(confirmPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(registerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(34, 34, 34))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(38, 38, 38)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(confirmPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(confirmPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGap(22, 22, 22)
										.addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addGap(18, 18, 18)
										.addComponent(aceptTermsCheckBox)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(showTermsButton)))
						.addGap(25, 25, 25))
				);
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox aceptTermsCheckBox;
	private javax.swing.JLabel confirmPasswordLabel;
	private javax.swing.JPasswordField confirmPasswordTF;
	private javax.swing.JLabel emailLabel;
	private javax.swing.JTextField emailTF;
	private javax.swing.JLabel passwordLabel;
	private javax.swing.JPasswordField passwordTF;
	private javax.swing.JButton registerButton;
	private javax.swing.JButton showTermsButton;
	private javax.swing.JTextField userNameTF;
	private javax.swing.JLabel usernameLabel;
	// End of variables declaration//GEN-END:variables
	private JFrame frame;
	private JPanel loginPanel;
	private Register register;
}
